project_id = "vqskeanwpnvuyxorymib"

[functions.search-patient-records]
verify_jwt = false

[functions.create-docs-prescription]
verify_jwt = false

[functions.translate-content]
verify_jwt = false

[functions.analyze-symptoms]
verify_jwt = false

[functions.get-autofill-medications]
enabled = true
verify_jwt = true
import_map = "./functions/get-autofill-medications/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-autofill-medications/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-autofill-medications/*.html" ]
