-- Create the analytics table
CREATE TABLE public.analytics (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    event_type text NOT NULL,
    path text NOT NULL,
    details jsonb
);

ALTER TABLE public.analytics OWNER TO postgres;

ALTER TABLE ONLY public.analytics
    ADD CONSTRAINT analytics_pkey PRIMARY KEY (id);

ALTER TABLE public.analytics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.analytics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Enable Row Level Security
ALTER TABLE public.analytics ENABLE ROW LEVEL SECURITY;

-- Create policy for anonymous inserts
CREATE POLICY "Enable insert for anonymous users" ON public.analytics FOR INSERT TO anon WITH CHECK (true);

-- Grant usage on the sequence to the anon role
GRANT USAGE, SELECT ON SEQUENCE public.analytics_id_seq TO anon;