CREATE TABLE "public"."post_translations" (
    "id" bigint NOT NULL,
    "post_id" bigint NOT NULL,
    "language" text NOT NULL,
    "title" text,
    "excerpt" text,
    "content" text,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "public"."post_translations" OWNER TO "postgres";

ALTER TABLE "public"."post_translations" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."post_translations_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."post_translations"
    ADD CONSTRAINT "post_translations_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."post_translations"
    ADD CONSTRAINT "post_translations_post_id_fkey" FOREIGN KEY (post_id) REFERENCES public.posts(id) ON DELETE CASCADE;

ALTER TABLE ONLY "public"."post_translations"
    ADD CONSTRAINT "post_translations_post_id_language_key" UNIQUE (post_id, language);
