// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/supabase-fallback';

const SUPABASE_URL = "https://vqskeanwpnvuyxorymib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxc2tlYW53cG52dXl4b3J5bWliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MDMwMDcsImV4cCI6MjA2Mzk3OTAwN30.ICS_onpmI7Zdyqzx3ZP9_H_L8O4h7HRDhqbjWC3tBLk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);